baseurl = "https://joebraasch.github.io/PopUpTestSite/"
themesDir = "themes"
theme = "hugo-geo"
publishDir = "docs"
relativeURLs = false
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "shortcode-here"
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "Joseph.Braasch@ndsu.edu"

	profilepic = "img/Leaves.jpg"
	
	title = "PopUp Poplars"
	subtitle = "Common Gardens for Research and Education"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/alexurquhart"
	[[params.socialbuttons]]
	faicon = "twitter"
	url = "https://twitter.com/alexanderurq"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://linkedin.com"
	[[params.socialbuttons]]
	faicon = "google-plus"
	url = "https://plus.google.com/+YourID"

	[[params.navlinks]]
	name = "About"
	url = "about"
	
	[[params.navlinks]]
	name = "Blog"
	url = ""
	
	[[params.navlinks]]
	name = "Tutorials"
	url = "tutorial/"